### ISSUE TITLE
HTML correct closing tag brakes the embed parser

### ISSUE THREAD

**Issue by kiwi1342** [ritz078/embed-js#238]
If leaving HTML tags inline with the embed URL, the parser won't work.

So this won't work:
```
<p>https://www.instagram.com/p/BSGXM0DjFc6/?taken-by=barrefaeli</p>
```

Instead this will:

```
<p>https://www.instagram.com/p/BSGXM0DjFc6/?taken-by=barrefaeli
    </p>
```

You can see the issue here:

http://codepen.io/kiwi1342/pen/OpBBZX

**Comment by ritz078** [comment]
should be fixed in v5
